# Generated by Django 4.2.7 on 2023-12-02 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('Updated_at', models.DateField(auto_now_add=True, null=True)),
                ('order_number', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('order_date', models.DateField()),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='customer.customer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
