# Generated by Django 4.2.7 on 2023-12-02 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('Updated_at', models.DateField(auto_now_add=True, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
